services:
  ue:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      public_net:
        ipv4_address: 192.168.7.1
    entrypoint: /bin/bash -c \
      "ip route add 192.168.8.1/8 via 192.168.7.2; ip route; sleep infinity"
    command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
    # depends_on:
    #   compressor:
    #     condition: service_healthy
    #   decompressor:
    #     condition: service_healthy

  compressor:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      public_net:
        ipv4_address: 192.168.7.2
    entrypoint: /bin/bash -c \
      "ip route add 192.168.8.1/8 via 192.168.7.3; ip route; sleep infinity"
    command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  decompressor:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      public_net:
        ipv4_address: 192.168.7.3
    entrypoint: /bin/bash -c \
      "ip route add 192.168.7.1/8 via 192.168.7.2; ip route; sleep infinity"
    command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  ext:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c \
      "ip route add 192.168.7.1/8 via 192.168.7.3; ip route; sleep infinity"
    command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
    networks:
      public_net:
        ipv4_address: 192.168.8.1
    # depends_on:
    #   compressor:
    #     condition: service_healthy
    #   decompressor:
    #     condition: service_healthy

networks:
  public_net:
    driver: bridge
    name: rohc-public-net
    ipam:
      config:
        - subnet: 192.168.7.128/16
    driver_opts:
      com.docker.network.bridge.name: "rohc-net"